GDAL_ROOT	=	..\..

!INCLUDE $(GDAL_ROOT)\nmake.opt

default:	build
	xcopy /D  /Y $(ARCHITECTURE)\$(CONFIGURATION)\*.obj ..\o

build:
	@echo $(CONFIGURATION) $(ARCHITECTURE)
	msbuild index.sln /t:Rebuild /p:Configuration=$(CONFIGURATION);Platform=$(ARCHITECTURE) /m:6
	
clean:
	msbuild index.sln /t:Clean /p:Configuration=$(CONFIGURATION);Platform=$(ARCHITECTURE) /m:6
